name: CI
on:
  push:
  pull_request:

jobs:
  pre_ci:
    uses: dtolnay/.github/.github/workflows/pre_ci.yml@master
  build:
    runs-on: ubuntu-latest
    needs: pre_ci
    if: needs.pre_ci.outputs.continue
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: uwumarie
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build
