name: Build Docker Image
on:
  push:
    branches:
      - main

jobs:
  pre_ci:
    uses: dtolnay/.github/.github/workflows/pre_ci.yml@master
  build:
    if: needs.pre_ci.outputs.continue
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: uwumarie
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          OCI_ARCHIVE=$(nix build .#docker)
          DOCKER_REPOSITORY="docker://ghcr.io/${GITHUB_REPOSITORY,,}"
          skopeo copy --dest-creds="$GITHUB_ACTOR:$GITHUB_TOKEN" "docker-archive:${OCI_ARCHIVE}" "$DOCKER_REPOSITORY"
        env:
          GITHUB_TOKEN: ${{ github.token }}
